[package]
name = "usage"
version = "0.1.0"
edition = "2021"

[dependencies]
automapper = { path = "../automapper" }
lazy-to-map-derive = { path = "../derive" }
rustdoc-json = { workspace = true }
grpc-build-core = "0.3.0"

[build-dependencies]
grpc-build = "6.1.1"
